"""add Department

Revision ID: 26da09d2f48f
Revises: 7633cc654649
Create Date: 2025-04-10 20:06:01.077400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26da09d2f48f'
down_revision = '7633cc654649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
